=== sqdp-specs/squad-convert/test/northwind/content/schema0/table4/table4.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.admin.ch/xmlns/siard/1.0/schema0/table4.xsd" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.admin.ch/xmlns/siard/1.0/schema0/table4.xsd">
  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="row" type="rowType">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="rowType">
    <xs:sequence>
      <xs:element name="c1" type="xs:integer"/>
      <xs:element name="c2" type="xs:string"/>
      <xs:element name="c3" type="xs:string"/>
      <xs:element minOccurs="0" name="c4" type="xs:string"/>
      <xs:element minOccurs="0" name="c5" type="xs:string"/>
      <xs:element minOccurs="0" name="c6" type="xs:dateTime"/>
      <xs:element minOccurs="0" name="c7" type="xs:dateTime"/>
      <xs:element minOccurs="0" name="c8" type="xs:string"/>
      <xs:element minOccurs="0" name="c9" type="xs:string"/>
      <xs:element minOccurs="0" name="c10" type="xs:string"/>
      <xs:element minOccurs="0" name="c11" type="xs:string"/>
      <xs:element minOccurs="0" name="c12" type="xs:string"/>
      <xs:element minOccurs="0" name="c13" type="xs:string"/>
      <xs:element minOccurs="0" name="c14" type="xs:string"/>
      <xs:element minOccurs="0" name="c15" type="blobType"/>
      <xs:element minOccurs="0" name="c16" type="clobType"/>
      <xs:element minOccurs="0" name="c17" type="xs:integer"/>
      <xs:element minOccurs="0" name="c18" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="clobType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="file" type="xs:string"/>
        <xs:attribute name="length" type="xs:integer"/>
	    <xs:attribute name="messageDigest" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="blobType">
    <xs:simpleContent>
      <xs:extension base="xs:hexBinary">
        <xs:attribute name="file" type="xs:string"/>
        <xs:attribute name="length" type="xs:integer"/>
	    <xs:attribute name="messageDigest" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== sqdp-specs/squad-convert/test/northwind/content/schema0/table4/table4.xml
<?xml version="1.0" encoding="utf-8"?>
<table xmlns="http://www.admin.ch/xmlns/siard/1.0/schema0/table4.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.admin.ch/xmlns/siard/1.0/schema0/table4.xsd table4.xsd">
  <row><c1>1</c1><c2>Davolio</c2><c3>Nancy</c3><c4>Sales Representative</c4><c5>Ms.</c5><c6>1948-12-07T23:00:00.000000000</c6><c7>1992-04-30T22:00:00.000000000</c7><c8>507 - 20th Ave. E.\u000D\u000AApt. 2A</c8><c9>Seattle</c9><c10>WA</c10><c11>98122</c11><c12>USA</c12><c13>(206) 555-9857</c13><c14>5467</c14><c15 file="Northwind_lobseg_0/content/schema0/table4/lob15/record0.bin" length="12315" messageDigest="md5af1c21d8a01777470a52851def9db1c5"/><c16>Education includes a BA in psychology from Colorado State University in 1970. \u0020She also completed "The Art of the Cold Call." \u0020Nancy is a member of Toastmasters International.</c16><c17>2</c17><c18>http://accweb/emmployees/davolio.bmp</c18></row>
  <row><c1>2</c1><c2>Fuller</c2><c3>Andrew</c3><c4>Vice President, Sales</c4><c5>Dr.</c5><c6>1952-02-18T23:00:00.000000000</c6><c7>1992-08-13T22:00:00.000000000</c7><c8>908 W. Capital Way</c8><c9>Tacoma</c9><c10>WA</c10><c11>98401</c11><c12>USA</c12><c13>(206) 555-9482</c13><c14>3457</c14><c15 file="Northwind_lobseg_0/content/schema0/table4/lob15/record1.bin" length="12295" messageDigest="md593d7eb0220fdb69bb0c9f4385c741f12"/><c16>Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981. \u0020He is fluent in French and Italian and reads German. \u0020He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993. \u0020Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.</c16><c18>http://accweb/emmployees/fuller.bmp</c18></row>
  <row><c1>3</c1><c2>Leverling</c2><c3>Janet</c3><c4>Sales Representative</c4><c5>Ms.</c5><c6>1963-08-29T23:00:00.000000000</c6><c7>1992-03-31T22:00:00.000000000</c7><c8>722 Moss Bay Blvd.</c8><c9>Kirkland</c9><c10>WA</c10><c11>98033</c11><c12>USA</c12><c13>(206) 555-3412</c13><c14>3355</c14><c15 file="Northwind_lobseg_0/content/schema0/table4/lob15/record2.bin" length="11372" messageDigest="md5f5498d7caa5a2eb55786643a75b6b61c"/><c16>Janet has a BS degree in chemistry from Boston College (1984). \u0020She has also completed a certificate program in food retailing management. \u0020Janet was hired as a sales associate in 1991 and promoted to sales representative in February 1992.</c16><c17>2</c17><c18>http://accweb/emmployees/leverling.bmp</c18></row>
  <row><c1>4</c1><c2>Peacock</c2><c3>Margaret</c3><c4>Sales Representative</c4><c5>Mrs.</c5><c6>1937-09-18T23:00:00.000000000</c6><c7>1993-05-02T22:00:00.000000000</c7><c8>4110 Old Redmond Rd.</c8><c9>Redmond</c9><c10>WA</c10><c11>98052</c11><c12>USA</c12><c13>(206) 555-8122</c13><c14>5176</c14><c15 file="Northwind_lobseg_0/content/schema0/table4/lob15/record3.bin" length="12121" messageDigest="md58e1a6c431ad8a2b25e5e19bee7649de8"/><c16>Margaret holds a BA in English literature from Concordia College (1958) and an MA from the American Institute of Culinary Arts (1966). \u0020She was assigned to the London office temporarily from July through November 1992.</c16><c17>2</c17><c18>http://accweb/emmployees/peacock.bmp</c18></row>
  <row><c1>5</c1><c2>Buchanan</c2><c3>Steven</c3><c4>Sales Manager</c4><c5>Mr.</c5><c6>1955-03-03T23:00:00.000000000</c6><c7>1993-10-16T23:00:00.000000000</c7><c8>14 Garrett Hill</c8><c9>London</c9><c11>SW1 8JR</c11><c12>UK</c12><c13>(71) 555-4848</c13><c14>3453</c14><c15 file="Northwind_lobseg_0/content/schema0/table4/lob15/record4.bin" length="12163" messageDigest="md5f4a0848773e3ad7b87d2d27340869b8d"/><c16>Steven Buchanan graduated from St. Andrews University, Scotland, with a BSC degree in 1976. \u0020Upon joining the company as a sales representative in 1992, he spent 6 months in an orientation program at the Seattle office and then returned to his permanent post in London. \u0020He was promoted to sales manager in March 1993. \u0020Mr. Buchanan has completed the courses "Successful Telemarketing" and "International Sales Management." \u0020He is fluent in French.</c16><c17>2</c17><c18>http://accweb/emmployees/buchanan.bmp</c18></row>
  <row><c1>6</c1><c2>Suyama</c2><c3>Michael</c3><c4>Sales Representative</c4><c5>Mr.</c5><c6>1963-07-01T23:00:00.000000000</c6><c7>1993-10-16T23:00:00.000000000</c7><c8>Coventry House\u000D\u000AMiner Rd.</c8><c9>London</c9><c11>EC2 7JR</c11><c12>UK</c12><c13>(71) 555-7773</c13><c14>428</c14><c15 file="Northwind_lobseg_0/content/schema0/table4/lob15/record5.bin" length="11872" messageDigest="md5e3f6993081df534b23f22607c514ce6a"/><c16>Michael is a graduate of Sussex University (MA, economics, 1983) and the University of California at Los Angeles (MBA, marketing, 1986). \u0020He has also taken the courses "Multi-Cultural Selling" and "Time Management for the Sales Professional." \u0020He is fluent in Japanese and can read and write French, Portuguese, and Spanish.</c16><c17>5</c17><c18>http://accweb/emmployees/davolio.bmp</c18></row>
  <row><c1>7</c1><c2>King</c2><c3>Robert</c3><c4>Sales Representative</c4><c5>Mr.</c5><c6>1960-05-28T23:00:00.000000000</c6><c7>1994-01-01T23:00:00.000000000</c7><c8>Edgeham Hollow\u000D\u000AWinchester Way</c8><c9>London</c9><c11>RG1 9SP</c11><c12>UK</c12><c13>(71) 555-5598</c13><c14>465</c14><c15 file="Northwind_lobseg_0/content/schema0/table4/lob15/record6.bin" length="11899" messageDigest="md57f123f42616160cce2eeef2d1fd7d48e"/><c16>Robert King served in the Peace Corps and traveled extensively before completing his degree in English at the University of Michigan in 1992, the year he joined the company. \u0020After completing a course entitled "Selling in Europe," he was transferred to the London office in March 1993.</c16><c17>5</c17><c18>http://accweb/emmployees/davolio.bmp</c18></row>
  <row><c1>8</c1><c2>Callahan</c2><c3>Laura</c3><c4>Inside Sales Coordinator</c4><c5>Ms.</c5><c6>1958-01-08T23:00:00.000000000</c6><c7>1994-03-04T23:00:00.000000000</c7><c8>4726 - 11th Ave. N.E.</c8><c9>Seattle</c9><c10>WA</c10><c11>98105</c11><c12>USA</c12><c13>(206) 555-1189</c13><c14>2344</c14><c15 file="Northwind_lobseg_0/content/schema0/table4/lob15/record7.bin" length="11949" messageDigest="md50ad004fe137cf63835bba9418e32492d"/><c16>Laura received a BA in psychology from the University of Washington. \u0020She has also completed a course in business French. \u0020She reads and writes French.</c16><c17>2</c17><c18>http://accweb/emmployees/davolio.bmp</c18></row>
  <row><c1>9</c1><c2>Dodsworth</c2><c3>Anne</c3><c4>Sales Representative</c4><c5>Ms.</c5><c6>1966-01-26T23:00:00.000000000</c6><c7>1994-11-14T23:00:00.000000000</c7><c8>7 Houndstooth Rd.</c8><c9>London</c9><c11>WG2 7LT</c11><c12>UK</c12><c13>(71) 555-4444</c13><c14>452</c14><c15 file="Northwind_lobseg_0/content/schema0/table4/lob15/record8.bin" length="12203" messageDigest="md540a5309f5432d87cc9004ab4de65c868"/><c16>Anne has a BA degree in English from St. Lawrence College. \u0020She is fluent in French and German.</c16><c17>5</c17><c18>http://accweb/emmployees/davolio.bmp</c18></row>
</table>
